### ISSUE TITLE
Authentication if statement doesn't work

### ISSUE THREAD

**Issue by tslytsly** [simonjenny/fastcom#1]
Hi,
I'm trying to use this with MQTT auth, but it always attempts to publish un-authenticated.
Log shows:
`Sending Data to MQTT (MQTT) -  No Auth`

I edited the run script to use this logical check:
`if [ $MQTT_PASS ]; then`

then it works as expected.

Any chance you can amend this?

Thanks

**Comment by djismgaming** [comment]
I do have the same issue. Will try your workaround. Do you know which line should be changed?
